# File: src/agents/optimizer.py
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from src.agents.router import TaskComplexityRouter


@dataclass(slots=True)
class OptimizationResult:
    """Structured result returned by resume optimization routines."""

    optimized_resume: str
    rationale: list[str] = field(default_factory=list)
    model_name: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)


class ResumeOptimizer:
    """Agent facade for tailoring resumes to job descriptions."""

    def __init__(self, router: TaskComplexityRouter | None = None) -> None:
        self.router = router or TaskComplexityRouter()

    async def extract_resume_facts(self, resume_text: str) -> dict[str, Any]:
        """Extract stable candidate facts from resume text."""

        return {"raw_text": resume_text, "skills": [], "roles": [], "education": []}

    async def optimize_resume(self, resume_text: str, job_description: str) -> OptimizationResult:
        """Produce an optimized resume draft for a target job."""

        decision = self.router.select_model(
            prompt=f"Optimize resume for job: {job_description}",
            context={"job_description": job_description},
        )
        return OptimizationResult(
            optimized_resume=resume_text,
            rationale=["stub_optimizer_preserved_original_text"],
            model_name=decision.model_name,
            metadata={"complexity": decision.estimated_complexity},
        )

    async def generate_change_summary(self, original_text: str, optimized_text: str) -> list[str]:
        """Summarize differences between original and optimized resume text."""

        if original_text == optimized_text:
            return ["No changes generated by scaffold stub."]
        return ["Resume text was modified."]
