# File: src/agents/optimizer.py
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from src.clients.ollama import OllamaClient
from src.agents.router import TaskComplexityRouter


@dataclass(slots=True)
class OptimizationResult:
    """Structured result returned by resume optimization routines."""

    optimized_resume: str
    rationale: list[str] = field(default_factory=list)
    model_name: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)


class ResumeOptimizer:
    """Agent facade for tailoring resumes to job descriptions."""

    def __init__(self, router: TaskComplexityRouter | None = None, llm_client: OllamaClient | None = None) -> None:
        self.router = router or TaskComplexityRouter()
        self.llm_client = llm_client or OllamaClient()

    async def extract_resume_facts(self, resume_text: str) -> dict[str, Any]:
        """Extract stable candidate facts from resume text."""

        return {"raw_text": resume_text, "skills": [], "roles": [], "education": []}

    async def optimize_resume(
        self,
        resume_text: str,
        job_description: str,
        skills_to_highlight: list[str] | None = None,
        target_role: str | None = None,
    ) -> OptimizationResult:
        """Produce an optimized resume draft for a target job."""

        prompt = self._build_optimization_prompt(
            resume_text=resume_text,
            job_description=job_description,
            skills_to_highlight=skills_to_highlight or [],
            target_role=target_role,
        )
        decision = self.router.select_model(
            prompt=prompt,
            context={"job_description": job_description},
        )
        generation = await self.llm_client.generate(
            model=decision.model_name,
            system=(
                "You are a precise resume optimization assistant. Preserve truthful candidate facts. "
                "Do not invent employers, dates, degrees, metrics, or certifications."
            ),
            prompt=prompt,
        )
        optimized_resume = generation.text
        if generation.used_fallback or not optimized_resume:
            optimized_resume = self._local_optimization_fallback(resume_text, job_description, skills_to_highlight or [])

        return OptimizationResult(
            optimized_resume=optimized_resume,
            rationale=[
                "routed_to_local_ollama_model",
                "preserved_source_facts",
                "aligned_resume_language_to_job_description",
            ],
            model_name=decision.model_name,
            metadata={
                "routing": {
                    "model_tier": decision.model_tier.value,
                    "model_name": decision.model_name,
                    "reason": decision.reason,
                    "estimated_complexity": decision.estimated_complexity,
                },
                "llm": generation.metadata,
                "used_fallback": generation.used_fallback,
            },
        )

    async def generate_change_summary(self, original_text: str, optimized_text: str) -> list[str]:
        """Summarize differences between original and optimized resume text."""

        if original_text == optimized_text:
            return ["No changes generated by scaffold stub."]
        return ["Resume text was modified."]

    def _build_optimization_prompt(
        self,
        resume_text: str,
        job_description: str,
        skills_to_highlight: list[str],
        target_role: str | None = None,
    ) -> str:
        """Build a bounded prompt for Ollama resume optimization."""

        skills_line = ", ".join(skills_to_highlight) if skills_to_highlight else "No explicit skills provided."
        target_role_line = target_role or "Infer from job description."
        return (
            "Optimize the resume for the target job.\n\n"
            "Rules:\n"
            "- Keep only facts supported by the original resume.\n"
            "- Improve clarity, ordering, and keyword alignment.\n"
            "- Emphasize the user-selected skills only when the resume supports them.\n"
            "- Return only the rewritten resume text.\n\n"
            f"Target role: {target_role_line}\n"
            f"User-selected skills to emphasize: {skills_line}\n\n"
            f"Original resume:\n{resume_text}\n\n"
            f"Target job description:\n{job_description}\n"
        )

    def _local_optimization_fallback(
        self,
        resume_text: str,
        job_description: str,
        skills_to_highlight: list[str],
    ) -> str:
        """Create a deterministic optimized draft when Ollama is unavailable."""

        keywords = [word.strip(".,:;()[]").lower() for word in job_description.split()]
        unique_keywords = sorted({word for word in keywords if len(word) > 4})[:12]
        keyword_line = ", ".join(unique_keywords) if unique_keywords else "target role requirements"
        skills_line = ", ".join(skills_to_highlight) if skills_to_highlight else "not specified"
        return (
            "Optimized Resume Draft\n\n"
            f"Target Alignment Keywords: {keyword_line}\n\n"
            f"User-Selected Skills To Emphasize: {skills_line}\n\n"
            f"{resume_text.strip()}\n\n"
            "Targeted Summary\n"
            "Candidate profile aligned to the selected role while preserving the original resume facts."
        )
